---
refresh_interval: 2 # seconds
max_price: 9999 # dollars
urls:
  - https://www.amazon.co.uk/Oypla-Traditional-Folding-Hardwood-Deckchairs/dp/B00KRLN1QC/ref=sr_1_5?dchild=1&keywords=deck+chairs&qid=1607463278&sr=8-5
  - https://www.overclockers.co.uk/endgame-gear-xm1-rgb-usb-rgb-optical-esports-performance-gaming-mouse-white-egg-xm1rgb-wht-kb-007-eg.html
  - https://www.box.co.uk/910-005796-Logitech-G203-Lightsync-Gaming-Mouse_2938178.html
  - https://www.currys.co.uk/gbuk/home-appliances/floorcare/vacuum-cleaners/dyson-v11-absolute-cordless-vacuum-cleaner-blue-10204572-pdt.html?intcmp=home~Dyson-V11-Absolute~category-blocks%20four~2~n/a~BF~wk31~n/a
  - https://www.ebuyer.com/879087-eg-s83-90w-cpu-cooler-s83
  - https://www.novatech.co.uk/products/sandisk-extreme-portable-250gb-external-solid-state-drive-ssd/sdssde60-250g-g25.html
  - https://www.cclonline.com/product/232518/MLW-D12M-A20PW-R1/CPU-Coolers/Cooler-Master-MasterLiquid-Lite-120-Liquid-CPU-Cooler/CLR1519/
  - https://www.morecomputers.com/a?pid=BX8070110700K%3E%3EIntel
  - https://www.newegg.com/global/uk-en/blue-wd5000azlx-500gb/p/N82E16822236811
...
